version: "2"
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - godoclint
    - gomodguard
    - noinlineerr
    - paralleltest
    - testpackage
    - varnamelen
    - gochecknoglobals
    - cyclop
    - gocognit
    - nestif
    - wsl
    - wsl_v5
    - funlen
    - gosec
    - mnd
    - revive
    - goconst
  exclusions:
    rules:
      - path: _test\.go$
        linters:
          - err113
          - noctx
          - varnamelen
  formatters:
    enable:
      - gci
      - gofumpt
      - goimports
      - golines
