profile: cover.out

threshold:
  total: 90

override:
  - path: backends/git
    threshold: 100
  - path: backends/jj
    threshold: 100

exclude:
  paths:
    - main\.go$ # Program entry point
    - cmd/genreadme/
