coverage:
  status:
    project:
      default:
        target: 80%

component_management:
  individual_components:
    - component_id: backends_git
      name: backends/git
      paths:
        - backends/git/**
    - component_id: backends_jj
      name: backends/jj
      paths:
        - backends/jj/**
ignore:
  - main.go
  - cmd/genreadme/**
